"""initial_schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=False),
        sa.Column('product_requirement', sa.String(length=500), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('quantity_required', sa.Integer(), nullable=False),
        sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('delivery_timeline', sa.String(length=255), nullable=False),
        sa.Column('additional_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_category'), 'clients', ['category'], unique=False)
    op.create_index(op.f('ix_clients_location'), 'clients', ['location'], unique=False)

    op.create_table(
        'suppliers',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('supplier_name', sa.String(length=255), nullable=False),
        sa.Column('product_offered', sa.String(length=500), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('available_quantity', sa.Integer(), nullable=False),
        sa.Column('pricing_details', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('delivery_capability', sa.String(length=255), nullable=False),
        sa.Column('additional_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_category'), 'suppliers', ['category'], unique=False)
    op.create_index(op.f('ix_suppliers_location'), 'suppliers', ['location'], unique=False)

    op.create_table(
        'matches',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('client_id', sa.Uuid(), nullable=False),
        sa.Column('supplier_id', sa.Uuid(), nullable=False),
        sa.Column('match_score', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_client_id'), 'matches', ['client_id'], unique=False)
    op.create_index(op.f('ix_matches_supplier_id'), 'matches', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_supplier_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_client_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_suppliers_location'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_clients_location'), table_name='clients')
    op.drop_index(op.f('ix_clients_category'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
