/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as SuppliersNewRouteImport } from './routes/suppliers.new'
import { Route as ClientsIdDashboardRouteImport } from './routes/clients.$id.dashboard'
import { Route as ClientsEditIdRouteImport } from './routes/clients.edit.$id'
import { Route as SuppliersIdDashboardRouteImport } from './routes/suppliers.$id.dashboard'
import { Route as SuppliersEditIdRouteImport } from './routes/suppliers.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersNewRoute = SuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdDashboardRoute = ClientsIdDashboardRouteImport.update({
  id: '/clients/$id/dashboard',
  path: '/clients/$id/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsEditIdRoute = ClientsEditIdRouteImport.update({
  id: '/clients/edit/$id',
  path: '/clients/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdDashboardRoute = SuppliersIdDashboardRouteImport.update({
  id: '/suppliers/$id/dashboard',
  path: '/suppliers/$id/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersEditIdRoute = SuppliersEditIdRouteImport.update({
  id: '/suppliers/edit/$id',
  path: '/suppliers/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients/new': typeof ClientsNewRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/clients/$id/dashboard': typeof ClientsIdDashboardRoute
  '/clients/edit/$id': typeof ClientsEditIdRoute
  '/suppliers/$id/dashboard': typeof SuppliersIdDashboardRoute
  '/suppliers/edit/$id': typeof SuppliersEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients/new': typeof ClientsNewRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/clients/$id/dashboard': typeof ClientsIdDashboardRoute
  '/clients/edit/$id': typeof ClientsEditIdRoute
  '/suppliers/$id/dashboard': typeof SuppliersIdDashboardRoute
  '/suppliers/edit/$id': typeof SuppliersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients/new': typeof ClientsNewRoute
  '/suppliers/new': typeof SuppliersNewRoute
  '/clients/$id/dashboard': typeof ClientsIdDashboardRoute
  '/clients/edit/$id': typeof ClientsEditIdRoute
  '/suppliers/$id/dashboard': typeof SuppliersIdDashboardRoute
  '/suppliers/edit/$id': typeof SuppliersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clients/new'
    | '/suppliers/new'
    | '/clients/$id/dashboard'
    | '/clients/edit/$id'
    | '/suppliers/$id/dashboard'
    | '/suppliers/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clients/new'
    | '/suppliers/new'
    | '/clients/$id/dashboard'
    | '/clients/edit/$id'
    | '/suppliers/$id/dashboard'
    | '/suppliers/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clients/new'
    | '/suppliers/new'
    | '/clients/$id/dashboard'
    | '/clients/edit/$id'
    | '/suppliers/$id/dashboard'
    | '/suppliers/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientsNewRoute: typeof ClientsNewRoute
  SuppliersNewRoute: typeof SuppliersNewRoute
  ClientsIdDashboardRoute: typeof ClientsIdDashboardRoute
  ClientsEditIdRoute: typeof ClientsEditIdRoute
  SuppliersIdDashboardRoute: typeof SuppliersIdDashboardRoute
  SuppliersEditIdRoute: typeof SuppliersEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/new': {
      id: '/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof SuppliersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id/dashboard': {
      id: '/clients/$id/dashboard'
      path: '/clients/$id/dashboard'
      fullPath: '/clients/$id/dashboard'
      preLoaderRoute: typeof ClientsIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/edit/$id': {
      id: '/clients/edit/$id'
      path: '/clients/edit/$id'
      fullPath: '/clients/edit/$id'
      preLoaderRoute: typeof ClientsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id/dashboard': {
      id: '/suppliers/$id/dashboard'
      path: '/suppliers/$id/dashboard'
      fullPath: '/suppliers/$id/dashboard'
      preLoaderRoute: typeof SuppliersIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/edit/$id': {
      id: '/suppliers/edit/$id'
      path: '/suppliers/edit/$id'
      fullPath: '/suppliers/edit/$id'
      preLoaderRoute: typeof SuppliersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientsNewRoute: ClientsNewRoute,
  SuppliersNewRoute: SuppliersNewRoute,
  ClientsIdDashboardRoute: ClientsIdDashboardRoute,
  ClientsEditIdRoute: ClientsEditIdRoute,
  SuppliersIdDashboardRoute: SuppliersIdDashboardRoute,
  SuppliersEditIdRoute: SuppliersEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
